version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}"
      NODE_ENV: development
      PORT: 3000
      API_DOMAIN: ${API_DOMAIN}
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules
      - /home/dev/logs/:/root/.npm/_logs/

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
