name: Test CI
on:
  push:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Write .env
        run: 
          touch .env &&
          echo "DATABASE_URL=postgres://user:password@localhost/database" > .env &&
          echo "TOKEN_SECRET=secret" > .env

      - name: Write client .env
        run: 
          touch ./client/.env &&
          echo "API_DOMAIN=http://localhost:3000" > ./client/.env &&
          echo "TITLE_NAME=Rudy" > ./client/.env

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm install
      - name: Test
        run: |
          npm run test