name: Test CI
on:
  push:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Write docker.env
        run: 
          touch .env.docker &&
          echo "DB_USER=user" > .env.docker &&
          echo "DB_PASSWORD=password" >>.env.docker &&
          echo "DB_DATABASE=wishlist" >> .env.docker &&
          echo "API_DOMAIN=http://localhost:8005" >> .env.docker &&
          echo "TOKEN_SECRET=secret" >> .env.docker

      - name: Build the Docker image
        run: docker-compose --env-file .env.docker up --build -d
      - name: Run migrations
        run: docker exec wishlist_app_1 npm run migrations
      - name: Run Tests
        run: docker exec wishlist_app_1 npm run test